### ISSUE TITLE
s2i argument "--force-pull" is deprecated 

### ISSUE THREAD

**Issue by kyguy** [jboss-container-images/concreate-test-steps#6]
Causing some of the tests to fail with "ERROR:root:Error: unknown flag: --force-pull"
( http://pastebin.test.redhat.com/528610 ) when using the latest version of s2i (s2i v1.1.7).

Are we using a specific version on s2i? If not, I can remove the culpable argument

**Comment by rcernich** [comment]
I hit this too because the tests fail when using the 1.0.4 version that's installed on our dev machine.  That error is related to parsing the docker config file, which generates an npe/panic.
